# Monokai theme for Alacritty

[colors.primary]
background = "#272a30"
foreground = "#f8f8f0"

[colors.normal]
black = "#272a30"
red = "#f92672"
green = "#a6e22e"
yellow = "#e6db74"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#66d9ef"
white = "#f8f8f0"

[colors.bright]
black = "#4d5154"
red = "#f92672"
green = "#a6e22e"
yellow = "#e6db74"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#66d9ef"
white = "#ffffff"

[colors.selection]
background = "#4d5154"
foreground = "#f8f8f0"
