# Catppuccin Frappe theme for Alacritty

[colors.primary]
background = "#303446"
foreground = "#c6d0f5"

[colors.normal]
black = "#414559"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#b5bfe2"

[colors.bright]
black = "#51576d"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#a5adce"

[colors.selection]
background = "#51576d"
foreground = "#c6d0f5"
