# Monokai Machine theme for Alacritty

[colors.primary]
background = "#273136"
foreground = "#f2fffc"

[colors.normal]
black = "#3a4449"
red = "#ff6d7e"
green = "#a2e57b"
yellow = "#ffed72"
blue = "#7cd5f1"
magenta = "#baa0f8"
cyan = "#7cd5f1"
white = "#f2fffc"

[colors.bright]
black = "#6b7678"
red = "#ff6d7e"
green = "#a2e57b"
yellow = "#ffed72"
blue = "#7cd5f1"
magenta = "#baa0f8"
cyan = "#7cd5f1"
white = "#ffffff"

[colors.selection]
background = "#545f62"
foreground = "#f2fffc"
