# Monokai Ristretto theme for Alacritty

[colors.primary]
background = "#2c2525"
foreground = "#fff1f3"

[colors.normal]
black = "#403838"
red = "#fd6883"
green = "#adda78"
yellow = "#f9cc6c"
blue = "#85dacc"
magenta = "#a8a9eb"
cyan = "#85dacc"
white = "#fff1f3"

[colors.bright]
black = "#72696a"
red = "#fd6883"
green = "#adda78"
yellow = "#f9cc6c"
blue = "#85dacc"
magenta = "#a8a9eb"
cyan = "#85dacc"
white = "#ffffff"

[colors.selection]
background = "#5b5353"
foreground = "#fff1f3"
