# Retrobox theme for Alacritty

[colors.primary]
background = "#1c1c1c"
foreground = "#ebdbb2"

[colors.normal]
black = "#1c1c1c"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#fbf1c7"

[colors.selection]
background = "#504945"
foreground = "#ebdbb2"
