[general]
import=["~/dotfiles/themes/current/alacritty.toml"]

[window]
# opacity = 0.90
padding = { x = 10, y = 10 }
startup_mode = "Maximized"

decorations = "buttonless"
# blur = true
#

[cursor]
style = "Block"
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[[keyboard.bindings]]
key = "F"
mods = "Command|Shift"
action = "ToggleFullscreen"
