# Tokyo Night Moon theme for Alacritty

[colors.primary]
background = "#222436"
foreground = "#c8d3f5"

[colors.normal]
black = "#1b1d2b"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
blue = "#82aaff"
magenta = "#c099ff"
cyan = "#86e1fc"
white = "#828bb8"

[colors.bright]
black = "#444a73"
red = "#ff8d94"
green = "#c7fb6d"
yellow = "#ffd8ab"
blue = "#9ab8ff"
magenta = "#caabff"
cyan = "#b2ebff"
white = "#c8d3f5"

[colors.selection]
background = "#444a73"
foreground = "#c8d3f5"
